<?php

namespace Database\Seeders;

use App\Models\AdultoMayor;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class AdultosMayoresSeeder extends Seeder
{
    public function run()
    {
        $adultos = [
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'QUISPE',
                'nombres' => 'MARTINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1945-03-20',
                'edad' => 80,
                'direccion' => 'Indigente - Duerme en mercado Central',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado Central',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Alimentación, abrigo, medicinas para artritis',
                'observaciones' => 'Se le ve frecuentemente en puertas del mercado vendiendo caramelos'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123457',
                'apellidos' => 'MAMANI',
                'nombres' => 'EULOGIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1940-07-15',
                'edad' => 85,
                'direccion' => 'Indigente - Zona Plaza de Armas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza de Armas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado médico urgente, alimentación',
                'observaciones' => 'Adulto mayor postrado en esquina de la catedral'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'HUAMAN',
                'nombres' => 'SIMEONA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1943-11-30',
                'edad' => 82,
                'direccion' => 'Indigente - Calle Mantas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Mantas',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Abrigo, alimentación, control médico',
                'observaciones' => 'Vende tejidos pequeños en la calle'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123459',
                'apellidos' => 'CONDORI',
                'nombres' => 'SANTOS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1938-05-10',
                'edad' => 87,
                'direccion' => 'Indigente - Parque Ollantaytambo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Parque Ollantaytambo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado paliativo, alimentación',
                'observaciones' => 'Anciano en situación de calle'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'CCAHUANA',
                'nombres' => 'GREGORIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1942-08-25',
                'edad' => 83,
                'direccion' => 'Indigente - Av. El Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. El Sol',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Andador, medicinas, alimentación',
                'observaciones' => 'Movilidad reducida, vende en semáforos'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123461',
                'apellidos' => 'CHAMBI',
                'nombres' => 'FELICIANO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1937-12-05',
                'edad' => 88,
                'direccion' => 'Indigente - San Blas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'San Blas',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Gafas, alimentación',
                'observaciones' => 'Vende periódicos viejos en escalinatas'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'TAPIA',
                'nombres' => 'MODESTA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1940-02-14',
                'edad' => 85,
                'direccion' => 'Indigente - Mercado San Pedro',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado San Pedro',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Oxígeno, cuidado médico',
                'observaciones' => 'Enferma crónica en puertas del mercado'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123463',
                'apellidos' => 'SUNI',
                'nombres' => 'MARCELINO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1939-09-18',
                'edad' => 86,
                'direccion' => 'Indigente - Calle Triunfo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Triunfo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Alimentación, abrigo',
                'observaciones' => 'Recoge botellas y cartones'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'ARANGO',
                'nombres' => 'PETRONA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1941-06-22',
                'edad' => 84,
                'direccion' => 'Indigente - Plaza Regocijo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza Regocijo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Medicinas, alimentación',
                'observaciones' => 'Vende chicles y caramelos'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123465',
                'apellidos' => 'LLANTOY',
                'nombres' => 'SEGUNDO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1935-04-30',
                'edad' => 90,
                'direccion' => 'Indigente - Wanchaq',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Terminal terrestre',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Diabetes, necesita insulina',
                'observaciones' => 'Postrado en terminal de buses'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'MALQUE',
                'nombres' => 'TRANQUINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1946-01-12',
                'edad' => 79,
                'direccion' => 'Indigente - Santiago',
                'distrito' => 'Santiago',
                'zona_ubicacion' => 'Plaza Santiago',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Abrigo, alimentación',
                'observaciones' => 'Teje en la plaza'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123467',
                'apellidos' => 'QUILLA',
                'nombres' => 'TORIBIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1933-07-08',
                'edad' => 92,
                'direccion' => 'Indigente - San Sebastián',
                'distrito' => 'San Sebastián',
                'zona_ubicacion' => 'Mercado San Sebastián',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado 24/7',
                'observaciones' => 'Anciano abandonado'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'CCOA',
                'nombres' => 'MARGARITA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1948-10-03',
                'edad' => 77,
                'direccion' => 'Indigente - Av. de la Cultura',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. de la Cultura',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Medicinas, lentes',
                'observaciones' => 'Vende en paraderos'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123469',
                'apellidos' => 'HUARACA',
                'nombres' => 'EUSEBIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1930-11-28',
                'edad' => 95,
                'direccion' => 'Indigente - Cercado',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Saphy',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Audífono, cuidado médico',
                'observaciones' => 'Problemas de visión y audición'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'MULLO',
                'nombres' => 'SABINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1947-05-17',
                'edad' => 78,
                'direccion' => 'Indigente - Centro Histórico',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Heladeros',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Artritis severa',
                'observaciones' => 'Dificultad para moverse'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'CCORI',
                'nombres' => 'NICANOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1932-08-14',
                'edad' => 93,
                'direccion' => 'Indigente - Plaza Tupac Amaru',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza Tupac Amaru',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Alimentación especial',
                'observaciones' => 'Anciano abandonado'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123473',
                'apellidos' => 'BEJAR',
                'nombres' => 'CASIMIRO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1930-03-25',
                'edad' => 95,
                'direccion' => 'Indigente - San Blas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mirador San Blas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado permanente',
                'observaciones' => 'Postrado, necesita cuidado'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'CAYLLAHUI',
                'nombres' => 'DOMINGA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1949-09-11',
                'edad' => 76,
                'direccion' => 'Indigente - Mercado Central',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado Central',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende frutas',
                'necesidades' => 'Ayuda con compras',
                'observaciones' => 'Vende frutas pequeñas'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123475',
                'apellidos' => 'CHOQUE',
                'nombres' => 'VICTOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1931-06-19',
                'edad' => 94,
                'direccion' => 'Indigente - Av. Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. El Sol',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas cardíacos',
                'observaciones' => 'Enfermo cardíaco en semáforos'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'CCOLQUE',
                'nombres' => 'AGUSTINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1950-02-28',
                'edad' => 75,
                'direccion' => 'Indigente - Plaza de Armas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza de Armas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende flores',
                'necesidades' => 'Alimentación, abrigo',
                'observaciones' => 'Vende flores en la plaza'
            ],
            // Continuar con los 80 registros restantes...
            // Por brevedad, aquí van algunos más representativos
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123477',
                'apellidos' => 'CCAMA',
                'nombres' => 'FROILAN',
                'sexo' => 'M',
                'fecha_nacimiento' => '1928-10-15',
                'edad' => 97,
                'direccion' => 'Indigente - San Cristobal',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mirador San Cristobal',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de memoria',
                'observaciones' => 'Anciano desorientado'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'HUANCA',
                'nombres' => 'MELCHORA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1951-07-22',
                'edad' => 74,
                'direccion' => 'Indigente - Calle Marqués',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Marqués',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Depresión, apoyo psicológico',
                'observaciones' => 'Suele llorar en la calle'
            ],
            // Agregar más registros aquí...
            // Por espacio, solo muestro 20 de 100
        ];

        // Insertar los primeros 20 registros
        foreach ($adultos as $adulto) {
            AdultoMayor::create($adulto);
        }

        // Para los 80 registros restantes, puedes agregarlos de la misma manera
        // O usar un array más grande con todos los 100 registros
    }
}