<?php

namespace Database\Seeders;

use App\Models\AdultoMayor;
use Illuminate\Database\Seeder;

class AdultosMayoresSeeder extends Seeder
{
    public function run()
    {
        $adultos = [
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'QUISPE',
                'nombres' => 'MARTINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1945-03-20',
                'edad' => 80,
                'direccion' => 'Indigente - Duerme en mercado Central',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado Central',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Alimentación, abrigo, medicinas para artritis',
                'observaciones' => 'Se le ve frecuentemente en puertas del mercado vendiendo caramelos'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123457',
                'apellidos' => 'MAMANI',
                'nombres' => 'EULOGIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1940-07-15',
                'edad' => 85,
                'direccion' => 'Indigente - Zona Plaza de Armas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza de Armas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado médico urgente, alimentación',
                'observaciones' => 'Adulto mayor postrado en esquina de la catedral'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'HUAMAN',
                'nombres' => 'SIMEONA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1943-11-30',
                'edad' => 82,
                'direccion' => 'Indigente - Calle Mantas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Mantas',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Abrigo, alimentación, control médico',
                'observaciones' => 'Vende tejidos pequeños en la calle'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123459',
                'apellidos' => 'CONDORI',
                'nombres' => 'SANTOS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1938-05-10',
                'edad' => 87,
                'direccion' => 'Indigente - Parque Ollantaytambo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Parque Ollantaytambo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado paliativo, alimentación',
                'observaciones' => 'Anciano en situación de calle'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'CCAHUANA',
                'nombres' => 'GREGORIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1942-08-25',
                'edad' => 83,
                'direccion' => 'Indigente - Av. El Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. El Sol',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Andador, medicinas, alimentación',
                'observaciones' => 'Movilidad reducida, vende en semáforos'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123461',
                'apellidos' => 'CHAMBI',
                'nombres' => 'FELICIANO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1937-12-05',
                'edad' => 88,
                'direccion' => 'Indigente - San Blas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'San Blas',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Gafas, alimentación',
                'observaciones' => 'Vende periódicos viejos en escalinatas'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'TAPIA',
                'nombres' => 'MODESTA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1940-02-14',
                'edad' => 85,
                'direccion' => 'Indigente - Mercado San Pedro',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado San Pedro',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Oxígeno, cuidado médico',
                'observaciones' => 'Enferma crónica en puertas del mercado'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123463',
                'apellidos' => 'SUNI',
                'nombres' => 'MARCELINO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1939-09-18',
                'edad' => 86,
                'direccion' => 'Indigente - Calle Triunfo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Triunfo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Alimentación, abrigo',
                'observaciones' => 'Recoge botellas y cartones'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'ARANGO',
                'nombres' => 'PETRONA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1941-06-22',
                'edad' => 84,
                'direccion' => 'Indigente - Plaza Regocijo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza Regocijo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Medicinas, alimentación',
                'observaciones' => 'Vende chicles y caramelos'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123465',
                'apellidos' => 'LLANTOY',
                'nombres' => 'SEGUNDO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1935-04-30',
                'edad' => 90,
                'direccion' => 'Indigente - Wanchaq',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Terminal terrestre',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Diabetes, necesita insulina',
                'observaciones' => 'Postrado en terminal de buses'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'MALQUE',
                'nombres' => 'TRANQUINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1946-01-12',
                'edad' => 79,
                'direccion' => 'Indigente - Santiago',
                'distrito' => 'Santiago',
                'zona_ubicacion' => 'Plaza Santiago',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Abrigo, alimentación',
                'observaciones' => 'Teje en la plaza'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123467',
                'apellidos' => 'QUILLA',
                'nombres' => 'TORIBIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1933-07-08',
                'edad' => 92,
                'direccion' => 'Indigente - San Sebastián',
                'distrito' => 'San Sebastián',
                'zona_ubicacion' => 'Mercado San Sebastián',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado 24/7',
                'observaciones' => 'Anciano abandonado'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'CCOA',
                'nombres' => 'MARGARITA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1948-10-03',
                'edad' => 77,
                'direccion' => 'Indigente - Av. de la Cultura',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. de la Cultura',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Medicinas, lentes',
                'observaciones' => 'Vende en paraderos'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123469',
                'apellidos' => 'HUARACA',
                'nombres' => 'EUSEBIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1930-11-28',
                'edad' => 95,
                'direccion' => 'Indigente - Cercado',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Saphy',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Audífono, cuidado médico',
                'observaciones' => 'Problemas de visión y audición'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'MULLO',
                'nombres' => 'SABINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1947-05-17',
                'edad' => 78,
                'direccion' => 'Indigente - Centro Histórico',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Heladeros',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Artritis severa',
                'observaciones' => 'Dificultad para moverse'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'CCORI',
                'nombres' => 'NICANOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1932-08-14',
                'edad' => 93,
                'direccion' => 'Indigente - Plaza Tupac Amaru',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza Tupac Amaru',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Alimentación especial',
                'observaciones' => 'Anciano abandonado'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123473',
                'apellidos' => 'BEJAR',
                'nombres' => 'CASIMIRO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1930-03-25',
                'edad' => 95,
                'direccion' => 'Indigente - San Blas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mirador San Blas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado permanente',
                'observaciones' => 'Postrado, necesita cuidado'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'CAYLLAHUI',
                'nombres' => 'DOMINGA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1949-09-11',
                'edad' => 76,
                'direccion' => 'Indigente - Mercado Central',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado Central',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende frutas',
                'necesidades' => 'Ayuda con compras',
                'observaciones' => 'Vende frutas pequeñas'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123475',
                'apellidos' => 'CHOQUE',
                'nombres' => 'VICTOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1931-06-19',
                'edad' => 94,
                'direccion' => 'Indigente - Av. Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. El Sol',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas cardíacos',
                'observaciones' => 'Enfermo cardíaco en semáforos'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'CCOLQUE',
                'nombres' => 'AGUSTINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1950-02-28',
                'edad' => 75,
                'direccion' => 'Indigente - Plaza de Armas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza de Armas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende flores',
                'necesidades' => 'Alimentación, abrigo',
                'observaciones' => 'Vende flores en la plaza'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123477',
                'apellidos' => 'CCAMA',
                'nombres' => 'FROILAN',
                'sexo' => 'M',
                'fecha_nacimiento' => '1928-10-15',
                'edad' => 97,
                'direccion' => 'Indigente - San Cristobal',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mirador San Cristobal',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de memoria',
                'observaciones' => 'Anciano desorientado'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'HUANCA',
                'nombres' => 'MELCHORA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1951-07-22',
                'edad' => 74,
                'direccion' => 'Indigente - Calle Marqués',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Marqués',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Depresión, apoyo psicológico',
                'observaciones' => 'Suele llorar en la calle'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123479',
                'apellidos' => 'LLOCLLA',
                'nombres' => 'PRUDENCIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1927-04-08',
                'edad' => 98,
                'direccion' => 'Indigente - Hospital Regional',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Hospital Regional',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cáncer, tratamiento',
                'observaciones' => 'Enfermo terminal abandonado'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'MACHACA',
                'nombres' => 'SERAFINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1952-11-30',
                'edad' => 73,
                'direccion' => 'Indigente - Parque de la Madre',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Parque de la Madre',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Control médico',
                'observaciones' => 'Vende en el parque'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123481',
                'apellidos' => 'POMA',
                'nombres' => 'ELEUTERIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1925-01-17',
                'edad' => 100,
                'direccion' => 'Indigente - Terminal',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Terminal terrestre',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas respiratorios',
                'observaciones' => 'Usa oxígeno ocasionalmente'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'QUISPE',
                'nombres' => 'BASILIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1953-08-14',
                'edad' => 72,
                'direccion' => 'Indigente - San Sebastián',
                'distrito' => 'San Sebastián',
                'zona_ubicacion' => 'Mercado Modelo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende verduras',
                'necesidades' => 'Artrosis, dificultad para caminar',
                'observaciones' => 'Cojea al caminar'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123483',
                'apellidos' => 'SULLCA',
                'nombres' => 'ADAN',
                'sexo' => 'M',
                'fecha_nacimiento' => '1923-05-29',
                'edad' => 102,
                'direccion' => 'Indigente - Cusco',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Tigre',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado especializado',
                'observaciones' => 'Anciano mayor'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => null,
                'apellidos' => 'TINCO',
                'nombres' => 'CIRILA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1954-12-25',
                'edad' => 71,
                'direccion' => 'Indigente - Centro',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Almagro',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende empanadas',
                'necesidades' => 'Problemas de audición',
                'observaciones' => 'Vende comida en la calle'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => '40123485',
                'apellidos' => 'YUPANQUI',
                'nombres' => 'GUMERCINDO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1934-09-10',
                'edad' => 91,
                'direccion' => 'Indigente - Plaza',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Plaza San Francisco',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Parkinson, necesita ayuda',
                'observaciones' => 'Temblores constantes'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => null,
                'apellidos' => 'ZAPANA',
                'nombres' => 'DIONICIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1955-06-05',
                'edad' => 70,
                'direccion' => 'Indigente - Mercado',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado Central',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Revisión médica',
                'observaciones' => 'Teje gorros'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => '40123487',
                'apellidos' => 'ALCCAHUAMAN',
                'nombres' => 'HERMOGENES',
                'sexo' => 'M',
                'fecha_nacimiento' => '1936-02-20',
                'edad' => 89,
                'direccion' => 'Indigente - Cusco',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Plateros',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Cuidado especializado',
                'observaciones' => 'Anciano abandonado'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'CCORIMANYA',
                'nombres' => 'LIBRADA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1944-10-15',
                'edad' => 81,
                'direccion' => 'Indigente - Av. de la Cultura',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. de la Cultura',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Diabetes, control de dieta',
                'observaciones' => 'Vende en paraderos'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123489',
                'apellidos' => 'HUAMANTINCO',
                'nombres' => 'NATIVIDAD',
                'sexo' => 'M',
                'fecha_nacimiento' => '1938-07-31',
                'edad' => 87,
                'direccion' => 'Indigente - Cercado',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Saphy',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Problemas renales',
                'observaciones' => 'Recoge cartones'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'LLANQUECHAPA',
                'nombres' => 'OFELIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1947-04-26',
                'edad' => 78,
                'direccion' => 'Indigente - Mercado Central',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Mercado Central',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Hipertensión, control médico',
                'observaciones' => 'Sienta en puertas del mercado'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123491',
                'apellidos' => 'MALLQUI',
                'nombres' => 'PONCIANO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1937-11-11',
                'edad' => 88,
                'direccion' => 'Indigente - San Sebastián',
                'distrito' => 'San Sebastián',
                'zona_ubicacion' => 'Av. Tupac Amaru',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Compañía, conversación',
                'observaciones' => 'Vende periódicos viejos'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'PARCCO',
                'nombres' => 'QUINTINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1953-08-06',
                'edad' => 72,
                'direccion' => 'Indigente - San Blas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'San Blas',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Problemas circulatorios, ulceras varicosas',
                'observaciones' => 'Vende tejidos'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123493',
                'apellidos' => 'QUINTO',
                'nombres' => 'ROQUE',
                'sexo' => 'M',
                'fecha_nacimiento' => '1936-05-22',
                'edad' => 89,
                'direccion' => 'Indigente - Ruinas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Ruinas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Demencia senil, supervisión',
                'observaciones' => 'Desorientado frecuentemente'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'SACSARA',
                'nombres' => 'SIXTA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1954-01-17',
                'edad' => 71,
                'direccion' => 'Indigente - Collasuyo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Collasuyo',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende flores',
                'necesidades' => 'Actividades recreativas',
                'observaciones' => 'Vende flores artificiales'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123495',
                'apellidos' => 'TITO',
                'nombres' => 'TEOFILO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1935-09-02',
                'edad' => 90,
                'direccion' => 'Indigente - Choquechaca',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Choquechaca',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas prostáticos, dolor crónico',
                'observaciones' => 'Camina encorvado'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'USCA',
                'nombres' => 'URSULA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1955-06-28',
                'edad' => 70,
                'direccion' => 'Indigente - San Bernardo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle San Bernardo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Artritis reumatoide, medicación',
                'observaciones' => 'Vende en iglesias'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123497',
                'apellidos' => 'VILCA',
                'nombres' => 'VENANCIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1934-03-15',
                'edad' => 91,
                'direccion' => 'Indigente - Wanchaq',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Av. La Raza',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Critico',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Edad avanzada, cuidado paliativo',
                'observaciones' => 'Muy débil'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'YAHUAR',
                'nombres' => 'WENCESLAO',
                'sexo' => 'F',
                'fecha_nacimiento' => '1956-12-10',
                'edad' => 69,
                'direccion' => 'Indigente - Qanchipata',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Qanchipata',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Control médico preventivo',
                'observaciones' => 'Teje pulseras'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123499',
                'apellidos' => 'ZARATE',
                'nombres' => 'XAVIER',
                'sexo' => 'M',
                'fecha_nacimiento' => '1933-08-25',
                'edad' => 92,
                'direccion' => 'Indigente - Siete Angelitos',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Siete Angelitos',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Problemas digestivos, dieta especial',
                'observaciones' => 'Recoge plásticos'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => null,
                'apellidos' => 'ACHAHUI',
                'nombres' => 'YOLANDA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1957-07-20',
                'edad' => 68,
                'direccion' => 'Indigente - Pachacutec',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Pachacutec',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Problemas de tiroides, medicación hormonal',
                'observaciones' => 'Vende en colegios'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => '40123501',
                'apellidos' => 'CCANCHARI',
                'nombres' => 'ZACARIAS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1932-04-05',
                'edad' => 93,
                'direccion' => 'Indigente - Limacpampa',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Limacpampa',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía ocasional',
                'observaciones' => 'Sienta en bancas'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'HUARACA',
                'nombres' => 'ADELA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1958-11-30',
                'edad' => 67,
                'direccion' => 'Indigente - Nueva Baja',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Nueva Baja',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende frutas',
                'necesidades' => 'Problemas visuales, cataratas',
                'observaciones' => 'Vende frutas en mercados'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123503',
                'apellidos' => 'LLIUYA',
                'nombres' => 'BENITO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1931-01-15',
                'edad' => 94,
                'direccion' => 'Indigente - Ejército',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Ejército',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Fractura de cadera, rehabilitación',
                'observaciones' => 'Usa muletas'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'MORALES',
                'nombres' => 'CARLOTA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1959-08-10',
                'edad' => 66,
                'direccion' => 'Indigente - Garcilaso',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Garcilaso',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Actividades sociales',
                'observaciones' => 'Conversadora'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123505',
                'apellidos' => 'ÑAUPA',
                'nombres' => 'DAMASO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1930-05-26',
                'edad' => 95,
                'direccion' => 'Indigente - Marquez',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Marquez',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de sueño, insomnio crónico',
                'observaciones' => 'Duerme en parques'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'OCAMPO',
                'nombres' => 'ELVIRA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1960-02-20',
                'edad' => 65,
                'direccion' => 'Indigente - Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Sol',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Osteoporosis, riesgo de fracturas',
                'observaciones' => 'Camina con cuidado'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123507',
                'apellidos' => 'PAREDES',
                'nombres' => 'FIDEL',
                'sexo' => 'M',
                'fecha_nacimiento' => '1929-10-06',
                'edad' => 96,
                'direccion' => 'Indigente - Resbalosa',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Resbalosa',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Lectura de noticias',
                'observaciones' => 'Le gusta leer'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'QUISPE',
                'nombres' => 'GRACIELA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1961-07-02',
                'edad' => 64,
                'direccion' => 'Indigente - Mantas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Mantas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Ansiedad, apoyo emocional',
                'observaciones' => 'Nerviosa con extraños'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123509',
                'apellidos' => 'ROJAS',
                'nombres' => 'HILARIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1928-03-18',
                'edad' => 97,
                'direccion' => 'Indigente - Pardo',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Av. Pardo',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Enfermedad pulmonar obstructiva',
                'observaciones' => 'Tose frecuentemente'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'SALAS',
                'nombres' => 'IRMA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1962-12-13',
                'edad' => 63,
                'direccion' => 'Indigente - Tigre',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Tigre',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende flores',
                'necesidades' => 'Control médico rutinario',
                'observaciones' => 'Ama las plantas'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123511',
                'apellidos' => 'TORRES',
                'nombres' => 'JUSTO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1927-08-29',
                'edad' => 98,
                'direccion' => 'Indigente - Almagro',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Almagro',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de equilibrio, caídas frecuentes',
                'observaciones' => 'Usa bastón'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'URBANO',
                'nombres' => 'KARINA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1963-05-24',
                'edad' => 62,
                'direccion' => 'Indigente - Tullumayo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Tullumayo',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Depresión crónica, terapia',
                'observaciones' => 'Triste frecuentemente'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123513',
                'apellidos' => 'VALDIVIA',
                'nombres' => 'LEONCIO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1926-01-09',
                'edad' => 99,
                'direccion' => 'Indigente - Kiskapata',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Kiskapata',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Compañía para caminatas',
                'observaciones' => 'Le gusta caminar'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => null,
                'apellidos' => 'WAMAN',
                'nombres' => 'MIRIAM',
                'sexo' => 'F',
                'fecha_nacimiento' => '1964-10-04',
                'edad' => 61,
                'direccion' => 'Indigente - Siete Culebras',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Siete Culebras',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas auditivos, comunicación difícil',
                'observaciones' => 'No escucha bien'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => '40123515',
                'apellidos' => 'YARANGA',
                'nombres' => 'NESTOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1925-06-20',
                'edad' => 100,
                'direccion' => 'Indigente - Pardo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Pardo',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Desnutrición, necesita suplementos',
                'observaciones' => 'Muy delgado'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'ZAVALA',
                'nombres' => 'OLGA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1965-03-16',
                'edad' => 60,
                'direccion' => 'Indigente - Huayruropata',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Huayruropata',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Actividades manuales',
                'observaciones' => 'Teje bien'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123517',
                'apellidos' => 'ALVAREZ',
                'nombres' => 'PABLO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1924-11-01',
                'edad' => 101,
                'direccion' => 'Indigente - Nueva',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Nueva',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de presión arterial',
                'observaciones' => 'Control médico necesario'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'BRAVO',
                'nombres' => 'QUEEN',
                'sexo' => 'F',
                'fecha_nacimiento' => '1966-07-27',
                'edad' => 59,
                'direccion' => 'Indigente - Garcilaso',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Garcilaso',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Artritis severa, limitación motora',
                'observaciones' => 'Movilidad reducida'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123519',
                'apellidos' => 'CASTILLO',
                'nombres' => 'RAMIRO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1923-04-12',
                'edad' => 102,
                'direccion' => 'Indigente - Resbalosa',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Resbalosa',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía para ver televisión',
                'observaciones' => 'Le gusta TV'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'DIAZ',
                'nombres' => 'SANDRA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1967-01-07',
                'edad' => 58,
                'direccion' => 'Indigente - Marqués',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Marqués',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende frutas',
                'necesidades' => 'Problemas de columna, dolor crónico',
                'observaciones' => 'Dolor de espalda'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123521',
                'apellidos' => 'ESPINOZA',
                'nombres' => 'TOMAS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1922-08-23',
                'edad' => 103,
                'direccion' => 'Indigente - Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Sol',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Parkinson avanzado, temblores constantes',
                'observaciones' => 'Temblores visibles'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'FLORES',
                'nombres' => 'UNICA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1968-06-18',
                'edad' => 57,
                'direccion' => 'Indigente - Heladeros',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Heladeros',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Control médico general',
                'observaciones' => 'Salud estable'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123523',
                'apellidos' => 'GOMEZ',
                'nombres' => 'VICTOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1921-03-04',
                'edad' => 104,
                'direccion' => 'Indigente - Mantas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Pasaje Mantas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas renales, dieta estricta',
                'observaciones' => 'Dieta especial'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'HERRERA',
                'nombres' => 'WENDY',
                'sexo' => 'F',
                'fecha_nacimiento' => '1969-11-29',
                'edad' => 56,
                'direccion' => 'Indigente - Tejado',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Tejado',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Diabetes tipo 2, control glucémico',
                'observaciones' => 'Control de azúcar'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123525',
                'apellidos' => 'IBARRA',
                'nombres' => 'XAVIER',
                'sexo' => 'M',
                'fecha_nacimiento' => '1920-09-14',
                'edad' => 105,
                'direccion' => 'Indigente - La Paz',
                'distrito' => 'Santiago',
                'zona_ubicacion' => 'Av. La Paz',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía para conversar',
                'observaciones' => 'Conversador'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'JIMENEZ',
                'nombres' => 'YOLANDA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1970-04-10',
                'edad' => 55,
                'direccion' => 'Indigente - Zetas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Zetas',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Problemas circulatorios',
                'observaciones' => 'Mano frías'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123527',
                'apellidos' => 'LOPEZ',
                'nombres' => 'ZACARIAS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1919-12-26',
                'edad' => 106,
                'direccion' => 'Indigente - Alabado',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Alabado',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Demencia vascular, desorientación',
                'observaciones' => 'Se pierde fácil'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => null,
                'apellidos' => 'MARTINEZ',
                'nombres' => 'ANA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1971-09-21',
                'edad' => 54,
                'direccion' => 'Indigente - Huáscar',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Huáscar',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende flores',
                'necesidades' => 'Actividades recreativas',
                'observaciones' => 'Alegre'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => '40123529',
                'apellidos' => 'NUÑEZ',
                'nombres' => 'BERNARDO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1918-07-07',
                'edad' => 107,
                'direccion' => 'Indigente - Tordo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Tordo',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de próstata',
                'observaciones' => 'Dolor al orinar'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'OROZCO',
                'nombres' => 'CARLA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1972-02-01',
                'edad' => 53,
                'direccion' => 'Indigente - Pumacurco',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Pumacurco',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Fibromialgia, dolor generalizado',
                'observaciones' => 'Queja de dolores'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123531',
                'apellidos' => 'PEREZ',
                'nombres' => 'DANIEL',
                'sexo' => 'M',
                'fecha_nacimiento' => '1917-10-18',
                'edad' => 108,
                'direccion' => 'Indigente - Los Incas',
                'distrito' => 'San Sebastián',
                'zona_ubicacion' => 'Av. Los Incas',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Lectura acompañada',
                'observaciones' => 'Le gusta leer'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'QUIROZ',
                'nombres' => 'ELENA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1973-07-14',
                'edad' => 52,
                'direccion' => 'Indigente - Saphi',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Saphi',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas tiroideos',
                'observaciones' => 'Cuello inflamado'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123533',
                'apellidos' => 'RAMIREZ',
                'nombres' => 'FERNANDO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1916-05-30',
                'edad' => 109,
                'direccion' => 'Indigente - Triunfo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Triunfo',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Insuficiencia cardíaca',
                'observaciones' => 'Falta de aire'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'SILVA',
                'nombres' => 'GABRIELA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1974-12-25',
                'edad' => 51,
                'direccion' => 'Indigente - Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. El Sol',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Control médico preventivo',
                'observaciones' => 'Salud estable'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123535',
                'apellidos' => 'TAPIA',
                'nombres' => 'HECTOR',
                'sexo' => 'M',
                'fecha_nacimiento' => '1915-02-09',
                'edad' => 110,
                'direccion' => 'Indigente - Herrajes',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Herrajes',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas digestivos crónicos',
                'observaciones' => 'Dolor estomacal'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'URIBE',
                'nombres' => 'INES',
                'sexo' => 'F',
                'fecha_nacimiento' => '1975-09-04',
                'edad' => 50,
                'direccion' => 'Indigente - Plateros',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Plateros',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Esclerosis múltiple',
                'observaciones' => 'Dificultad para moverse'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123537',
                'apellidos' => 'VARGAS',
                'nombres' => 'JAVIER',
                'sexo' => 'M',
                'fecha_nacimiento' => '1914-06-20',
                'edad' => 111,
                'direccion' => 'Indigente - Cultura',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. de la Cultura',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía ocasional',
                'observaciones' => 'Solitario'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'WONG',
                'nombres' => 'KARLA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1976-03-16',
                'edad' => 49,
                'direccion' => 'Indigente - Purgatorio',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Purgatorio',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende frutas',
                'necesidades' => 'Problemas de ansiedad',
                'observaciones' => 'Nerviosa'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123539',
                'apellidos' => 'XUAREZ',
                'nombres' => 'LUIS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1913-11-01',
                'edad' => 112,
                'direccion' => 'Indigente - Santa Catalina',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Santa Catalina',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Enfermedad de Alzheimer',
                'observaciones' => 'No reconoce personas'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'YALICO',
                'nombres' => 'MARTA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1977-10-26',
                'edad' => 48,
                'direccion' => 'Indigente - Tupac Amaru',
                'distrito' => 'San Sebastián',
                'zona_ubicacion' => 'Av. Tupac Amaru',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Actividades sociales',
                'observaciones' => 'Sociable'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123541',
                'apellidos' => 'ZEGARRA',
                'nombres' => 'NORBERTO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1912-07-12',
                'edad' => 113,
                'direccion' => 'Indigente - San Agustín',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. San Agustín',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de movilidad',
                'observaciones' => 'Usa silla de ruedas'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => null,
                'apellidos' => 'ALANOCA',
                'nombres' => 'OFELIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1978-05-08',
                'edad' => 47,
                'direccion' => 'Indigente - Ruinas',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Ruinas',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Lupus eritematoso',
                'observaciones' => 'Manchas en piel'
            ],
            [
                'fecha_registro' => '2025-10-26',
                'dni' => '40123543',
                'apellidos' => 'BARRIGA',
                'nombres' => 'PEDRO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1911-01-23',
                'edad' => 114,
                'direccion' => 'Indigente - Collasuyo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Collasuyo',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía para escuchar música',
                'observaciones' => 'Le gusta música'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => null,
                'apellidos' => 'CARRASCO',
                'nombres' => 'QUENA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1979-12-18',
                'edad' => 46,
                'direccion' => 'Indigente - Choquechaca',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Choquechaca',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende flores',
                'necesidades' => 'Problemas de visión',
                'observaciones' => 'Usa lentes gruesos'
            ],
            [
                'fecha_registro' => '2025-10-20',
                'dni' => '40123545',
                'apellidos' => 'DURAN',
                'nombres' => 'RAUL',
                'sexo' => 'M',
                'fecha_nacimiento' => '1910-09-03',
                'edad' => 115,
                'direccion' => 'Indigente - San Bernardo',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle San Bernardo',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Enfermedad pulmonar obstructiva crónica',
                'observaciones' => 'Dificultad para respirar'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => null,
                'apellidos' => 'ESTRADA',
                'nombres' => 'SOFIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1980-06-29',
                'edad' => 45,
                'direccion' => 'Indigente - La Raza',
                'distrito' => 'Wanchaq',
                'zona_ubicacion' => 'Av. La Raza',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Control médico anual',
                'observaciones' => 'Salud buena'
            ],
            [
                'fecha_registro' => '2025-10-21',
                'dni' => '40123547',
                'apellidos' => 'FUENTES',
                'nombres' => 'TEO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1909-04-14',
                'edad' => 116,
                'direccion' => 'Indigente - Qanchipata',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Qanchipata',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de audición',
                'observaciones' => 'No oye bien'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => null,
                'apellidos' => 'GUTIERREZ',
                'nombres' => 'URSULA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1981-01-09',
                'edad' => 44,
                'direccion' => 'Indigente - Siete Angelitos',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Siete Angelitos',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Artritis reumatoide juvenil',
                'observaciones' => 'Dolor en articulaciones'
            ],
            [
                'fecha_registro' => '2025-10-22',
                'dni' => '40123549',
                'apellidos' => 'HURTADO',
                'nombres' => 'VICENTE',
                'sexo' => 'M',
                'fecha_nacimiento' => '1908-09-25',
                'edad' => 117,
                'direccion' => 'Indigente - Pachacutec',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Pachacutec',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía para paseos cortos',
                'observaciones' => 'Le gusta pasear'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => null,
                'apellidos' => 'IRIGOIN',
                'nombres' => 'WILMA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1982-08-20',
                'edad' => 43,
                'direccion' => 'Indigente - Limacpampa',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Limacpampa',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Vende dulces',
                'necesidades' => 'Problemas de columna',
                'observaciones' => 'Dolor de espalda'
            ],
            [
                'fecha_registro' => '2025-10-23',
                'dni' => '40123551',
                'apellidos' => 'JARA',
                'nombres' => 'XAVIER',
                'sexo' => 'M',
                'fecha_nacimiento' => '1907-05-06',
                'edad' => 118,
                'direccion' => 'Indigente - Nueva Baja',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Nueva Baja',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Recicla',
                'necesidades' => 'Demencia con cuerpos de Lewy',
                'observaciones' => 'Alucinaciones'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => null,
                'apellidos' => 'KOC',
                'nombres' => 'YOLANDA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1983-02-01',
                'edad' => 42,
                'direccion' => 'Indigente - Ejército',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Ejército',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Vende artesanías',
                'necesidades' => 'Actividades manuales',
                'observaciones' => 'Creativa'
            ],
            [
                'fecha_registro' => '2025-10-24',
                'dni' => '40123553',
                'apellidos' => 'LAZO',
                'nombres' => 'ZACARIAS',
                'sexo' => 'M',
                'fecha_nacimiento' => '1906-10-17',
                'edad' => 119,
                'direccion' => 'Indigente - Garcilaso',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Jr. Garcilaso',
                'lee_escribe' => 'No',
                'nivel_estudio' => 'Ninguno',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Regular',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Problemas de presión',
                'observaciones' => 'Mareos frecuentes'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => null,
                'apellidos' => 'MENA',
                'nombres' => 'ALICIA',
                'sexo' => 'F',
                'fecha_nacimiento' => '1984-07-13',
                'edad' => 41,
                'direccion' => 'Indigente - Marquez',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Calle Marquez',
                'lee_escribe' => 'Si',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Malo',
                'actividad_calle' => 'Vende periódicos',
                'necesidades' => 'Esclerosis lateral amiotrófica',
                'observaciones' => 'Debilidad muscular'
            ],
            [
                'fecha_registro' => '2025-10-25',
                'dni' => '40123555',
                'apellidos' => 'NAVARRO',
                'nombres' => 'BRUNO',
                'sexo' => 'M',
                'fecha_nacimiento' => '1905-03-29',
                'edad' => 120,
                'direccion' => 'Indigente - Sol',
                'distrito' => 'Cusco',
                'zona_ubicacion' => 'Av. Sol',
                'lee_escribe' => 'Poco',
                'nivel_estudio' => 'Primaria',
                'apoyo_familiar' => 'Ninguno',
                'estado_abandono' => 'Situación Calle',
                'telefono' => null,
                'estado_salud' => 'Bueno',
                'actividad_calle' => 'Pide limosna',
                'necesidades' => 'Compañía para ver películas',
                'observaciones' => 'Le gusta cine'
            ]
        ];

        foreach ($adultos as $adulto) {
            // TRUCO PRO: Generar coordenadas aleatorias en Cusco para que el mapa funcione
            $adulto['lat'] = -13.5319 + (mt_rand(-50, 50) / 10000);
            $adulto['lon'] = -71.9675 + (mt_rand(-50, 50) / 10000);

            // Asignar Riesgo automático según Salud (Lógica inteligente)
            if ($adulto['estado_salud'] == 'Critico') {
                $adulto['nivel_riesgo'] = 'Alto';
            } elseif ($adulto['estado_salud'] == 'Malo') {
                $adulto['nivel_riesgo'] = 'Medio';
            } else {
                $adulto['nivel_riesgo'] = 'Bajo';
            }

            AdultoMayor::create($adulto);
        }
    }
}